// Obj Dictionary with the accepted `commands`

exports.values = {
    nextactions: 'Next Actions',
    nextaction: 'Next Actions',
    next: 'Next Actions',
    athome: 'At Home',
    home: 'At Home',
    atwork: 'At Work',
    work: 'At Work',
    tocall: 'To Call',
    call: 'To Call',
    waitingfor: 'Waiting For',
    wait: 'Waiting For',
    someday: 'Someday',
    some: 'Someday',
    errands: 'Errands',
    err: 'Errands',
    //bill: 'Bills',
    //bills: 'Bills',
    rar: 'Read and Review',
    readandreview: 'Read and Review',
    internet: 'Internet Search',
    projects: "Projects",
    list: "Lists",
    lists: "Lists",
    display: "Shores",
    disp: "Shores",

    add: 'Add',
    help: 'Help',
    complete: 'Done',
    done: 'Done',
    delete: 'Delete',
    del: 'Delete',
    remove: 'Delete',
    rm: 'Delete',
    show: 'Record Information',
    update: 'Update',
    move: 'Update',
    mv: 'Update',
    load: 'Load',
},

exports.tasks = {
    next: 'nextaction',
    nextaction: 'nextaction',
    name: 'name',
    start: 'start_date',
    start_date: 'start_date',
    due: 'due_date',
    due_date: 'due_date',
    category: 'category',
    cat: 'category',
    complete: 'task_completed',
    done: 'task_completed',
};
